Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis 
X: INTEIRO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 PARA X DE 1 ATÉ 50 FACA
 
  SE(X % 5 = 0) ENTÃO
    ESCREVAL("SENAI")
    
  SENÃO
     ESCREVAL(X)
    
  FIMSE
 FIMPARA
Fimalgoritmo